### ISSUE TITLE
OpenBLAS thread affinity

### ISSUE THREAD

**Issue by carstenbauer** [carstenbauer/julia-dgemm-noctua#1]
While trying to understand the [bad scaling of Julia + OpenBLAS](https://github.com/carstenbauer/julia-dgemm-N2/blob/master/README.md) from a single socket to dual sockets, I'm starting to ask a fundamental question (again):

**How can one control the affinity of the OpenBLAS threads that Julia uses by default?**

I thought `OMP_PLACES`, `OMP_PROC_BIND`, and cousins would do it but that doesn't seem to be the case!? I tried to use a large `OMP_NUM_THREADS` but `OMP_PLACES={0}` to pin them all to the first core which should give bad performance, but it didn't... I might also have an idea why these env variables don't work: AFAICT we don't set `USE_OPENMP=1` in https://github.com/JuliaPackaging/Yggdrasil/blob/master/O/OpenBLAS/common.jl (perhaps for a good reason?). BTW, I also don't understand what `GEMM_MULTITHREADING_THRESHOLD=50` does. (@giordano, any idea on those points?)

But if I can't use those env variables, what else can I do? `taskset` and others are candidates but how to control only BLAS threads (and not Julia threads)?!

(cc @vchuravy)

**Comment by carstenbauer** [comment]
Found something about `GEMM_MULTITHREADING_THRESHOLD`: https://github.com/xianyi/OpenBLAS/issues/2052#issuecomment-471203258
Shouldn't be an issue here.

**Comment by carstenbauer** [comment]
This looks very promising: https://github.com/xianyi/OpenBLAS/pull/2547

Seems to be available in the OpenBLAS that ships with Julia:
```
➜  bauerc@n2login3 julia  nm -D libopenblas64_.so | grep openblas
000000000033efd0 T openblas_block_factor
000000000033e4e0 T openblas_fork_handler
000000000033ee70 T openblas_get_config64_
000000000033ef40 T openblas_get_corename64_
000000000033ee60 T openblas_get_num_procs_64_
000000000033e5f0 T openblas_get_num_procs64_
000000000033ee50 T openblas_get_num_threads_64_
000000000033e600 T openblas_get_num_threads64_
000000000033ef60 T openblas_get_parallel_64_
000000000033ef50 T openblas_get_parallel64_
000000000033eff0 T openblas_goto_num_threads_env
000000000033efe0 T openblas_num_threads_env
000000000033f000 T openblas_omp_num_threads_env
000000000033f010 T openblas_read_env
000000000033f4e0 T openblas_setaffinity
000000000033ee40 T openblas_set_num_threads_64_
000000000033fb50 T openblas_set_num_threads64_
000000000033efc0 T openblas_thread_timeout
000000000033efb0 T openblas_verbose
000000000033ef70 T openblas_warning
```

Question is how to call it: how to get `cpu_set_t` for `openblas_setaffinity(int thread_idx, size_t cpusetsize, cpu_set_t* cpu_set)`?

**Comment by carstenbauer** [comment]
Notes from playing around

```julia
"""
Sets thread affinity for OpenBLAS threads. `thread_idx` is in [0, openblas_get_num_threads()-1].
"""
function openblas_setaffinity(thread_idx, cpusetsize, cpu_set)
    @ccall "libopenblas64_.so".openblas_setaffinity(thread_idx::Culong, cpusetsize::Csize_t, cpu_set::Ccpu_set_t)::Cint
end
```

Maybe relevant:
* https://docs.rs/libc/latest/src/libc/unix/linux_like/linux/mod.rs.html#154
* https://docs.rs/julia-sys/0.1.1/x86_64-apple-darwin/julia_sys/struct.cpu_set_t.html
* https://utcc.utoronto.ca/~cks/space/blog/programming/CSometimesGoodAnswer
* https://github.com/carstenbauer/ThreadPinning.jl/blob/main/src/libs/libpthread.jl
* ...

**UPDATE:**

For now, as a hacky(?) workaround, `Ccpu_set_t` -> `NTuple{16, UInt64}` for the mask seems to work.

```julia
"""
Sets thread affinity for OpenBLAS threads. `thread_idx` is in [0, openblas_get_num_threads()-1].
"""
function openblas_setaffinity(thread_idx, cpusetsize, cpu_set)
    @ccall "libopenblas64_.so".openblas_setaffinity(thread_idx::Culong, cpusetsize::Csize_t, cpu_set::NTuple{16, UInt64})::Cint
end
```

**Comment by carstenbauer** [comment]
@vchuravy: Any idea how I can / should define `Ccpu_set_t` in Julia? Do I really need to create a lightweight C wrapper library around the relevant bits from `sched.h`? Is there a better way?

**Comment by vchuravy** [comment]
@jpsamaroo has used CBinding.jl to some success to get the linux kernel specific structs.

**Comment by carstenbauer** [comment]
@jpsamaroo anything that you can point me to? That'd be great.

**Comment by carstenbauer** [comment]
Inspired by Rust which, IIUC, just uses 16 x `UInt64` for `Ccpu_set_t` I [did the same](https://github.com/carstenbauer/ThreadPinning.jl/blob/main/src/libs/libpthread.jl#L8-L10) and added pthreads-based and `openblas` pinning functionality to ThreadPinning.jl (https://github.com/carstenbauer/ThreadPinning.jl/blob/main/src/libs/libpthread.jl and https://github.com/carstenbauer/ThreadPinning.jl/blob/main/src/blas.jl#L44).

**Julia pthreads demo**
```julia
julia> using ThreadPinning

julia> println(getcpuids())
[37, 38, 24, 25, 22, 23, 26, 39, 20, 21]

julia> ThreadPinning.pthread_print_affinity_masks()
|11111111111111111111|11111111111111111111|
|11111111111111111111|11111111111111111111|
|11111111111111111111|11111111111111111111|
|11111111111111111111|11111111111111111111|
|11111111111111111111|11111111111111111111|
|11111111111111111111|11111111111111111111|
|11111111111111111111|11111111111111111111|
|11111111111111111111|11111111111111111111|
|11111111111111111111|11111111111111111111|
|11111111111111111111|11111111111111111111|

julia> ThreadPinning.pthread_pinthreads(0:9)

julia> println(getcpuids())
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

julia> ThreadPinning.pthread_print_affinity_masks()
|10000000000000000000|00000000000000000000|
|01000000000000000000|00000000000000000000|
|00100000000000000000|00000000000000000000|
|00010000000000000000|00000000000000000000|
|00001000000000000000|00000000000000000000|
|00000100000000000000|00000000000000000000|
|00000010000000000000|00000000000000000000|
|00000001000000000000|00000000000000000000|
|00000000100000000000|00000000000000000000|
|00000000010000000000|00000000000000000000|
```

**OpenBLAS pthreads demo**
```julia
julia> using LinearAlgebra

julia> A = rand(1000,1000); B = rand(1000,1000); C = zeros(1000,1000);

julia> @time mul!(C, A, B);
  0.764100 seconds (2.83 M allocations: 138.086 MiB, 19.02% gc time, 96.79% compilation time)

julia> @time mul!(C, A, B);
  0.004448 seconds

julia> using ThreadPinning

julia> ThreadPinning.nblasthreads()
10

julia> ThreadPinning.openblas_pinthreads(fill(0,10)) # pin all to CPU-core 0 (bad)

julia> @time mul!(C, A, B);
  0.130029 seconds

julia> @time mul!(C, A, B);
  0.136487 seconds

julia> ThreadPinning.openblas_pinthreads(:compact) # pin to CPU-cores 0-9 (good)

julia> @time mul!(C, A, B);
  0.005599 seconds

julia> @time mul!(C, A, B);
  0.004357 seconds
```

Would be great to be able to query the affinity mask of the OpenBLAS pthreads but that's currently not supported. I [opened an upstream issue](https://github.com/xianyi/OpenBLAS/issues/3687).

I'll close this issue, since this is good enough for now. However, let me mention that pinning OpenBLAS threads explicitly didn't change the findings in this repo (it still doesn't scale at all to dual-socket). Will track this in a separate issue.

**Comment by carstenbauer** [comment]
Update: seems like `openblas_getaffinity` will be in OpenBLAS 0.3.21 🎉  (https://github.com/xianyi/OpenBLAS/pull/3702)
