### ISSUE TITLE
Julia OpenBLAS doesn't scale to two sockets

### ISSUE THREAD

**Issue by carstenbauer** [carstenbauer/julia-dgemm-noctua#2]
In my [benchmarks](https://github.com/carstenbauer/julia-dgemm-noctua/tree/master/Noctua2/OpenBLAS), I find that `dgemm` performance of Julia + the OpenBLAS it ships doesn't scale at all to two sockets:
| BLAS | # cores | size | GFLOPS |
|---------------------|-----------|-------|------|
| OpenBLAS 0.3.17 (Julia)    | 128 cores | 10240 | **2287** |
| OpenBLAS 0.3.17 (Julia)     | 64 cores  | 10240 | 2239 |
| OpenBLAS 0.3.20 (C)    | 128 cores | 16384 | 3806 |

* I see the same [on another system](https://github.com/carstenbauer/julia-dgemm-noctua/tree/master/Noctua1/OpenBLAS), so doesn't seem to be system dependent.
* Other BLAS libraries (MKL.jl, BLISBLAS.jl) show the expected scaling, [see here](https://github.com/carstenbauer/julia-dgemm-noctua).
* **C + OpenBLAS works**: if I do a similar benchmark in C, where I use OpenBLAS from the easybuild module `numlib/OpenBLAS/0.3.20-GCC-11.2.0` and just call `cblas_dgemm`, I get the expected scaling as well (slightly below 4TFLOPS for 128 cores).

That raises the question: Why doesn't Julia + OpenBLAS scale to two sockets?
* Maybe because of the [compile options](https://github.com/JuliaPackaging/Yggdrasil/blob/master/O/OpenBLAS/common.jl#L51) we choose for our shipped OpenBLAS?
* Hard to imagine, but is OpenBLAS 0.3.20 so much better?!

**Comment by carstenbauer** [comment]
I tried to `BLAS.lbt_forward` to the system-wide OpenBLAS used in my C benchmark but unfortunately that doesn't work (why?!):
```julia
julia> using LinearAlgebra

julia> A = rand(1000,1000); B = rand(1000,1000); C = zeros(1000,1000);

julia> BLAS.get_config()
LinearAlgebra.BLAS.LBTConfig
Libraries:
└ [ILP64] libopenblas64_.so

julia> mul!(C, A, B);

julia> BLAS.lbt_forward(joinpath(ENV["EBROOTOPENBLAS"], "lib64", "libopenblas.so"), clear=true)
4860

julia> BLAS.get_config().loaded_libs[1].libname
"/cm/shared/apps/pc2/EB-SW/software/OpenBLAS/0.3.20-GCC-11.2.0/lib64/libopenblas.so"

julia> mul!(C, A, B);
Error: no BLAS/LAPACK library loaded!
```

These are the dgemm symbols:
```
➜  bauerc@ln-0002 lib64  nm -D libopenblas.so | grep dgemm
00000000000b92e0 T cblas_dgemm
00000000000b7720 T dgemm_
00000000003582b0 T dgemm_beta
000000000035bb90 T dgemm_incopy
000000000035d9e0 T dgemm_itcopy
0000000000358540 T dgemm_kernel
000000000017f180 T dgemm_nn
000000000017f710 T dgemm_nt
000000000035dfb0 T dgemm_oncopy
000000000035e820 T dgemm_otcopy
0000000000e39a28 D dgemm_p
0000000000e39a00 D dgemm_q
0000000000e399d8 D dgemm_r
00000000003a54b0 T dgemm_small_kernel_b0_nn
00000000003a8ca0 T dgemm_small_kernel_b0_nt
00000000003ab640 T dgemm_small_kernel_b0_tn
00000000003ad330 T dgemm_small_kernel_b0_tt
0000000000399920 T dgemm_small_kernel_nn
000000000039d560 T dgemm_small_kernel_nt
00000000003a0700 T dgemm_small_kernel_tn
00000000003a2510 T dgemm_small_kernel_tt
00000000003998c0 T dgemm_small_matrix_permit
0000000000198730 T dgemm_thread_nn
00000000001999a0 T dgemm_thread_nt
000000000019ac60 T dgemm_thread_tn
000000000019bee0 T dgemm_thread_tt
000000000017fcd0 T dgemm_tn
00000000001802a0 T dgemm_tt
```

**Comment by carstenbauer** [comment]
I pretty much ruled out thread pinning issues of the OpenBLAS threads with the tools described in https://github.com/carstenbauer/julia-dgemm-noctua/issues/1. Results don't change much (if at all) when pinning OpenBLAS threads compactly or spread.

**Comment by giordano** [comment]
> but unfortunately that doesn't work (why?!)

Is it ILP64?

**Comment by carstenbauer** [comment]
Don't think so. It also shows up as LP64 in `BLAS.get_config()`. Why?

**Comment by giordano** [comment]
> Why?

Because Julia's BLAS interface at the moment assumes ILP64, LP64 won't work: https://github.com/JuliaLang/LinearAlgebra.jl/issues/891

**Comment by carstenbauer** [comment]
Oh I didn't know. Given that libblastrampoline can handle both, I thought that Julia does as well. Thanks for the pointer.

**Comment by carstenbauer** [comment]
cc @ViralBShah because you always seem to be interested in these BLAS/LAPACK related things 🙂

**Comment by ViralBShah** [comment]
0.3.17 and 0.3.20 are probably a couple of years apart. I would expect there to be a huge difference in kernel quality for newer architectures and also threading. Can you try Julia with 0.3.20?

**Comment by ViralBShah** [comment]
Try using OpenBLAS32 I'd you want LP64.

**Comment by carstenbauer** [comment]
I ran the same benchmark with a self-compiled OpenBLAS v0.3.20 and v0.3.17 (`make -j 15 INTERFACE64=1 USE_THREAD=1 NO_AFFINITY=1 GEMM_MULTITHREADING_THRESHOLD=50 NO_STATIC=1 BINARY=64 DYNAMIC_ARCH=1`). This is what I got:

| BLAS | # cores | size | GFLOPS |
|---------------------|-----------|-------|------|
| OpenBLAS 0.3.17 (shipped)    | 40 cores | 10240 | **1032** |
| OpenBLAS 0.3.17 (shipped)     | 20 cores  | 10240 | 1176 |
| OpenBLAS 0.3.20 (jll)    | 40 cores | 10240 | 1478 |
| OpenBLAS 0.3.20 (jll)     | 20 cores  | 10240 | 1195 |
|---------------------|-----------|-------|------|
| OpenBLAS 0.3.17 (Julia, custom)    | 40 cores | 10240 | 1891 |
| OpenBLAS 0.3.17 (Julia, custom)     | 20 cores  | 10240 | 1411 |
| OpenBLAS 0.3.20 (Julia, custom)    | 40 cores | 10240 | 1902 |
| OpenBLAS 0.3.20 (Julia, custom)     | 20 cores  | 10240 | 1420 |
| OpenBLAS 0.3.17 (Julia, custom, dynamic arch)    | 40 cores | 10240 | 1905 |
| OpenBLAS 0.3.17 (Julia, custom, dynamic arch)     | 20 cores  | 10240 | 1141 |
| OpenBLAS 0.3.20 (Julia, custom, dynamic arch)    | 40 cores | 10240 | 1598 |
| OpenBLAS 0.3.20 (Julia, custom, dynamic arch)     | 20 cores  | 10240 | 1059 |

(Note that this is on Noctua 1 instead of Noctua 2 so it doesn't quantitatively compare to the OP.)

@ViralBShah I conclude from this
* that the lack of scaling can't be explained by a difference in OpenBLAS versions, and
* that the default OpenBLAS (Yggdrasil) might have suboptimal build options (maybe the cross compilation settings cause this? maybe we can / can't do anything about it?)

**Comment by ViralBShah** [comment]
Can you file this in `julialang/julia`? If there is a compilation/compiler issue, we need to track it down.

**Comment by ViralBShah** [comment]
What about Julia 0.3.20 shipped? A few releases ago, we used to compile openblas with fewer max threads for memory utilization, something we relaxed recently.

**Comment by carstenbauer** [comment]
> What about Julia 0.3.20 shipped?

By "shipped" I meant the OpenBLAS that is delivered by default. And Julia 1.8 ships 0.3.17. But I guess you mean OpenBLAS_jll@0.3.20? I've added it to the table above.

Given the new result, I find the initial timings for shipped v0.3.17 a bit strange. I have a feeling that there might be a contribution from me not running things on precisely the same node but just submitting it to the SLURM partition. I'll try to improve the benchmark in the next few days and then rerun everything before filing an issue over in the julia repo.

**Comment by ViralBShah** [comment]
1.8 is supposed to ship 0.3.20, I think: https://github.com/JuliaLang/julia/blob/release-1.8/stdlib/OpenBLAS_jll/Project.toml

**Comment by carstenbauer** [comment]
> 1.8 is supposed to ship 0.3.20, I think: [JuliaLang/julia@`release-1.8`/stdlib/OpenBLAS_jll/Project.toml](https://github.com/JuliaLang/julia/blob/release-1.8/stdlib/OpenBLAS_jll/Project.toml?rgh-link-date=2022-07-20T14%3A31%3A00Z)

Interesting. What about this then? https://github.com/JuliaLang/julia/blob/release-1.8/deps/Versions.make#L82

**Comment by carstenbauer** [comment]
Here the new numbers (I increased the sample size and ran all benchmarks on the exact same node of the cluster):

| BLAS | # cores | size | GFLOPS |
|---------------------|-----------|-------|------|
| Intel MKL v2022.0.0 (JLL) | 40 cores | 10240 | 2081 |
| Intel MKL v2022.0.0 (JLL) | 20 cores  | 10240 | 1054 |
| BLIS 0.9.0 (JLL)          | 40 cores | 10240 | 1890 |
| BLIS 0.9.0 (JLL)          | 20 cores  | 10240 | 990 |
| Octavian 0.3.15     | 40 cores | 10240 | **1053** |
| Octavian 0.3.15     | 20 cores  | 10240 | 1016 |
| OpenBLAS (shipped with Julia 1.8)    | 40 cores | 10240 | **1092** |
| OpenBLAS (shipped with Julia 1.8)     | 20 cores  | 10240 | 1063 |
|---------------------|-----------|-------|------|
| OpenBLAS 0.3.17 (custom)    | 40 cores | 10240 | 1908 |
| OpenBLAS 0.3.17 (custom)     | 20 cores  | 10240 | 1439 |
| OpenBLAS 0.3.20 (custom)    | 40 cores | 10240 | 1897 |
| OpenBLAS 0.3.20 (custom)     | 20 cores  | 10240 | 1444 |
|---------------------|-----------|-------|------|
| OpenBLAS 0.3.17 (JLL)    | 40 cores | 10240 | 1437 |
| OpenBLAS 0.3.17 (JLL)     | 20 cores  | 10240 | 1124 |
| OpenBLAS 0.3.20 (JLL)    | 40 cores | 10240 | 1535 |
| OpenBLAS 0.3.20 (JLL)     | 20 cores  | 10240 | 1185 |

What is particularly curious is that using OpenBLAS_jll manually is strictly better (both in terms of numbers and scaling) than the default/shipped OpenBLAS. It's still worse than a custom build of OpenBLAS.

**Comment by giordano** [comment]
> Interesting. What about this then? https://github.com/JuliaLang/julia/blob/release-1.8/deps/Versions.make#L82

There are indeed mismatches, but if you want to know the version of the JLL (relevant if you're using official binaries) you have to look at project file Viral linked.

**Comment by carstenbauer** [comment]
Let's discuss this further over at https://github.com/JuliaLang/LinearAlgebra.jl/issues/936. Closing this for now.
